name: Call Trivy
on:
 push:
   branches: [main]
 pull_request:
jobs:
 scan:
   name: Scan
   uses: the-mottled-oyster/actions/.github/workflows/reusable-trivy.yml@new-trivy
   with:
      image: 'ghcr.io/the-mottled-oyser/wordsmith-api:latest'
